import { useState } from 'react';

const faqs = [
  {
    category: 'Getting Started',
    emoji: '\uD83D\uDE80',
    items: [
      {
        q: 'What is Fablecast?',
        a: 'Fablecast is a daily children\u2019s story subscription. Every morning, we generate 18 fresh, fully illustrated and narrated stories across 6 character series and 3 languages. It\u2019s like having a new storybook delivered to your doorstep each day \u2014 but digital and instant.'
      },
      {
        q: 'Who is Fablecast for?',
        a: 'Fablecast is designed for parents and guardians of children aged 3\u20138. The stories are created with age-appropriate language, gentle themes, and engaging illustrations perfect for bedtime reading or independent exploration.'
      },
      {
        q: 'How do I sign up?',
        a: 'Click "Get Started" on the landing page and sign in with your Google account. You\u2019ll choose a plan and preferred language, and you\u2019re ready to go. No separate password to remember.'
      },
      {
        q: 'Is there a free trial?',
        a: 'Yes! The Free plan gives you access to 2 sample books with the full reading experience \u2014 illustrations, text, and audio \u2014 so you can see if Fablecast is right for your family before subscribing.'
      }
    ]
  },
  {
    category: 'Stories & Content',
    emoji: '\uD83D\uDCDA',
    items: [
      {
        q: 'How are the stories made?',
        a: 'Each story is generated by AI using carefully crafted character bibles that define the characters, art styles, world rules, and tone. The AI writes the text, generates unique illustrations, and creates audio narration. Safety guardrails ensure all content is age-appropriate.'
      },
      {
        q: 'How many stories do I get?',
        a: 'A new story is generated daily for each series you have access to. On the Knight and Emperor plans, that\u2019s 6 new stories every single day. On Squire, it\u2019s 1 new story per day from your chosen series.'
      },
      {
        q: 'Can I re-read past stories?',
        a: 'Yes! Stories remain in your library after generation. You can revisit any story from your subscription period anytime.'
      },
      {
        q: 'What languages are available?',
        a: 'Currently: English, Turkish, and Japanese. We\u2019re actively working on adding Spanish, Portuguese, German, and French \u2014 stay tuned to our blog for updates.'
      },
      {
        q: 'Are the stories safe for kids?',
        a: 'Absolutely. Every character series has built-in world rules that prevent inappropriate themes or settings. Stories are designed to be warm, positive, and encouraging. We continuously review and improve our safety parameters.'
      }
    ]
  },
  {
    category: 'Subscription & Billing',
    emoji: '\uD83D\uDCB3',
    items: [
      {
        q: 'Can I cancel anytime?',
        a: 'Yes. You can cancel your subscription at any time through your account settings. You\u2019ll keep full access until the end of your current billing period, then your account reverts to the Free plan.'
      },
      {
        q: 'Are there refunds?',
        a: 'Subscription payments are non-refundable with no prorated refunds for partial months. We encourage trying the Free plan first to make sure Fablecast is a good fit.'
      },
      {
        q: 'Can I switch plans?',
        a: 'Yes. You can upgrade or downgrade at any time. Plan changes take effect at the start of your next billing cycle.'
      },
      {
        q: 'Can I change my preferred series or language?',
        a: 'You can change your preferred character series (Squire plan) or language once per month. Changes apply to the next day\u2019s story generation.'
      }
    ]
  },
  {
    category: 'Technical',
    emoji: '\u2699\uFE0F',
    items: [
      {
        q: 'What devices can I use?',
        a: 'Fablecast stories are web-based and work on any modern browser \u2014 phones, tablets, laptops, and desktops. No app download required. Stories are designed mobile-first for the best tablet/phone reading experience.'
      },
      {
        q: 'Can I read offline?',
        a: 'Stories are packaged as PWA-ready web books. Once loaded, they can be saved to your home screen and accessed offline on supported devices.'
      },
      {
        q: 'Is there audio narration?',
        a: 'Yes! All stories include AI-generated narration with progressive text reveal. Audio is available on all paid plans, with the Emperor plan including the highest quality multi-language narration.'
      }
    ]
  },
  {
    category: 'Privacy & Safety',
    emoji: '\uD83D\uDD12',
    items: [
      {
        q: 'What data do you collect?',
        a: 'Only the minimum necessary: your email (from Google Sign-In), display name, and your chosen preferences (language, series). We don\u2019t collect any data from children directly, and we don\u2019t track browsing behavior.'
      },
      {
        q: 'Are there ads?',
        a: 'No. Fablecast is ad-free and will remain ad-free for the lifetime of the product. Your family\u2019s reading time will never be interrupted by advertisements.'
      },
      {
        q: 'Do you sell my data?',
        a: 'Never. We don\u2019t sell, rent, or trade personal data. See our Privacy Policy for full details.'
      }
    ]
  }
];

function FAQItem({ item }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-dashed border-plumMist/15 last:border-b-0">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center justify-between gap-4 py-4 text-left transition hover:text-twilight"
      >
        <span className="font-semibold text-cosmos">{item.q}</span>
        <span
          className={`shrink-0 text-lg text-twilight transition-transform ${open ? 'rotate-45' : ''}`}
        >
          +
        </span>
      </button>
      {open && (
        <p className="pb-4 pr-8 text-sm leading-relaxed text-cosmos/75">{item.a}</p>
      )}
    </div>
  );
}

export default function FAQ() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-14 lg:px-8">
      <div className="text-center">
        <span className="sticker border-starlight bg-starlight/10 text-cosmos">{'\u2753'} Help</span>
        <h1 className="mt-4 font-display text-4xl text-cosmos">Frequently Asked Questions</h1>
        <p className="mx-auto mt-4 max-w-xl text-lg text-cosmos/70">
          Everything you need to know about Fablecast.
        </p>
      </div>

      <div className="mt-12 space-y-10">
        {faqs.map((section) => (
          <div key={section.category}>
            <h2 className="flex items-center gap-2 font-display text-2xl text-cosmos">
              <span>{section.emoji}</span>
              {section.category}
            </h2>
            <div className="mt-4 rounded-2xl border-2 border-dashed border-plumMist/15 bg-white/60 px-5">
              {section.items.map((item) => (
                <FAQItem key={item.q} item={item} />
              ))}
            </div>
          </div>
        ))}
      </div>

      <div className="mt-14 rounded-[2rem] border-2 border-dashed border-lavender/30 bg-gradient-to-br from-lavender/10 to-sky/10 p-8 text-center">
        <span className="text-4xl">{'\uD83D\uDCEC'}</span>
        <h2 className="mt-3 font-display text-2xl text-cosmos">Still Have Questions?</h2>
        <p className="mx-auto mt-3 max-w-md text-cosmos/70">
          We&rsquo;d love to help. Reach out to us anytime.
        </p>
        <p className="mt-3 font-semibold text-twilight">support@fablecast.kids</p>
      </div>
    </article>
  );
}
